### ISSUE TITLE
Postgres 10: Wrong type of primary key in schema dump

### ISSUE THREAD

**Issue by felixbuenemann** [SchemaPlus/schema_plus_core#22]
It appears schema_plus_core 2.1.1 has some problems when dumping primary keys on PostgreSQL 10.0.

I have a `users` table with the default rails integer primary keys:

**Column:** id
**Type:** integer
**Nullable:** not null
**Default:** nextval('users_id_seq'::regclass)

However `rake db:schema:dump`on Rails 5.1.4 produces:

```diff
-  create_table "users", force: :cascade do |t|
+  create_table "users", id: :serial, default: %q{nextval('users_id_seq'::regclass)}, force: :cascade do |t|
```

So for some reason schema_plus_core thinks the type is now `:serial` instead of `:integer`.

If the schema is dumped on PostgreSQL 9.6.5 the result is fine.

**Comment by felixbuenemann** [comment]
I tried dumping without schema plus and it also dumps the id as `:serial`, so it looks like this is a problem in activerecord.

**Comment by felixbuenemann** [comment]
I should've read the postgres docs:

> The data types smallserial, serial and bigserial are not true types, but merely a notational convenience for creating unique identifier columns (similar to the AUTO_INCREMENT property supported by some other databases). In the current implementation, specifying:

```sql
CREATE TABLE tablename (
    colname SERIAL
);
```

is equivalent to specifying:

```sql
CREATE SEQUENCE tablename_colname_seq;
CREATE TABLE tablename (
    colname integer NOT NULL DEFAULT nextval('tablename_colname_seq')
);
ALTER SEQUENCE tablename_colname_seq OWNED BY tablename.colname;
```

So while the `id: :serial` generated by activerecord 5.1.4 is fine, the `default: %q{nextval('users_id_seq'::regclass)}` which is only dumped by schema_plus_core is redundant.

**Comment by mergulhao** [comment]
Same here. Also reported here: https://github.com/rails/rails/issues/30298

**Comment by alencarandre** [comment]
I have other project that I do not use schema_plus and I has the same error. Seems to me that problem is on rails 5.1

**Comment by urkle** [comment]
@alencarandre @felixbuenemann @mergulhao can any of you re-test this on the latest schema plus core (2.2.1) and see if it is still an issue?

**Comment by felixbuenemann** [comment]
Yepp, still happens with rails 5.1.6.1, schema_plus_core 2.2.1, schema_plus_indexes 0.3.1, schema_plus_pg_indexes 0.3.2 and postgres 10.4.

**Comment by urkle** [comment]
I was able to recreate this against PG 9.6 as well.  So it is not specific to PG 10.  I have a fix I'm working on now.

**Comment by urkle** [comment]
I've release Schema+ Core 2.2.2 which fixes this issue.

**Comment by milgner** [comment]
I'm encountering this issue with `schema_plus_core` 2.2.3, Rails 5.1.7 and PostgreSQL 11.5. Any recommendations?
I tried downgrading SPC to 2.2.2, just in case there was a regression but that did not help.
