### ISSUE TITLE
Support Rails 5

### ISSUE THREAD

**Issue by ronen** [SchemaPlus/schema_plus_core#9]
Creating the issue...

...if anybody out there in github-land is interested in working on Rails 5 support for SchemaPlus, please let me know.  I myself am a bit swamped these days so would welcome a collaborator stepping in. 
(I haven't even looked into whether this would be hard or trivial.)

Thanks!

**Comment by ronen** [comment]
Latest:  I've made a branch "activerecord-5.0", which includes AR 5.0 in the test matrix, but aside from that haven't changed anything.   And, unsurprisingly, it fails.  See https://travis-ci.org/SchemaPlus/schema_plus_core/builds/124089884

**Comment by ronen** [comment]
...and again, if there's anybody out there who has the time to look into this, that'd be great.  I'd be happy to help out of course.

**Comment by md5** [comment]
I've been looking in to using this with AR 5 and I've run into the following problems so far with a Postgres database:

1. The internal `prepare_column_options` method no longer takes a second parameter for `types` (cf. https://github.com/rails/rails/pull/17576)
2. The AR 5 dumper will now include indexes in the `create_table` statement with `t.index` if the adapter supports it (cf. https://github.com/rails/rails/pull/19994 and https://github.com/rails/rails/pull/23557). This breaks the column dumping code here: https://github.com/SchemaPlus/schema_plus_core/blob/970bf76/lib/schema_plus/core/active_record/schema_dumper.rb#L70-L78

The first one is easy to fix by changing the signature of `prepare_column_options` from `prepare_column_options(column, types)` to `prepare_column_options(column, *)` to accommodate both AR 4 and AR 5. I can provide a PR for this change if you're interested.

The second one will require some additional coding to have a special case for `t.index` and handle it appropriately. This is going to be a bit more work to get right and potentially error prone.

**Comment by md5** [comment]
I've opened https://github.com/SchemaPlus/schema_plus_core/pull/12 for the first issue with `prepare_column_options`

**Comment by ronen** [comment]
@md5 Thanks -- you're a hero!

**Comment by md5** [comment]
As discussed above and briefly in #12 and in my earlier comment, AR5 now has an `index_in_create` method in `SchemaDumper` that adds each index inside the `create_table` statement as `t.index ...`. It still has the `indexes` method as well, but that's only used for indexes that are not on normal tables (the comment in the source mentions materialized views).

I'm not sure what the right fix is for this, but this seems as good a place to discuss as any.

**Comment by ronen** [comment]
I took a look at `indexes_in_create` ([activerecord/lib/active_record/schema_dumper.rb#L207](https://github.com/rails/rails/blob/d0c257f5daadc2b3451f0b8c775f38c48c56eaad/activerecord/lib/active_record/schema_dumper.rb#L207)).  

I think the thing to do would be to provide an override similar to the override of `indexes()` at https://github.com/SchemaPlus/schema_plus_core/blob/970bf76/lib/schema_plus/core/active_record/schema_dumper.rb#L84.   I think the override of `indexes_in_create` could just about be identical, except for tweaking the regex to match `t.table` syntax.   Probably the `env` and `Index` objects should each get an extra boolean flag to indicate that the view was dumped inline.

Then schema_plus_core's (re)dumper at https://github.com/SchemaPlus/schema_plus_core/blob/970bf76a4e9fe97fa07c91523d6b7af74ceef8e5/lib/schema_plus/core/schema_dump.rb#L71 could dump any indexes flagged as inline using `t.index`, and the code at https://github.com/SchemaPlus/schema_plus_core/blob/970bf76a4e9fe97fa07c91523d6b7af74ceef8e5/lib/schema_plus/core/schema_dump.rb#L75 would only dump those that are not flagged as inline.

Does that all seems sensible?

Speaking of materialized views, there's an outstanding issue #6 which should probably be dealt with; and we should see what happens with them and their indexes in schema_plus_core + AR 5.

**Comment by md5** [comment]
Yes, that seems sensible.

**Comment by md5** [comment]
BTW, the problem in #6 doesn't seem to be related to materialized views, but rather to query-defined tables (I'm not sure what they're officially called). The materialized view implementations I'm familiar with use `CREATE MATERIALIZED VIEW`, not `CREATE TABLE`.

**Comment by md5** [comment]
@ronen Just wanted to follow up on this and let you know that I haven't had time to look into this further. For the time being, I'm just using `execute()` to manipulate my enum types directly.

**Comment by rhymes** [comment]
Any news? I saw that https://github.com/SchemaPlus/schema_plus_core/pull/14 has been merged in schema_plus_core

**Comment by boazy** [comment]
@rhymes
schema_plus_core fully supports AR5 on the latest version, but not all other schema_plus gems have been updated to support it yet. Unfortunately, AR5 introduced many incompatible changes, so in most cases just changing the dependency version numbers is not enough.

This issue tracks all the currently updated gems:
https://github.com/SchemaPlus/schema_plus/issues/229
